# Generated by Django 6.0.3 on 2026-04-06 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_session_id', models.UUIDField(blank=True, help_text='UUID assigned to a guest session when no user is logged in', null=True)),
                ('interview_style', models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('mixed', 'Mixed')], default='technical', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='questions.question')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user'], name='interview_s_user_id_e1117b_idx'), models.Index(fields=['anonymous_session_id'], name='interview_s_anonymo_78fcfe_idx'), models.Index(fields=['status'], name='interview_s_status_9ea885_idx')],
            },
        ),
    ]
