# Generated by Django 6.0.3 on 2026-04-04 18:24

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Full problem statement in Markdown')),
                ('constraints', models.TextField(blank=True, help_text='Edge cases and constraints, kept separate for agent context')),
                ('examples', models.JSONField(default=list, help_text='[{"input": "...", "output": "...", "explanation": "..."}]')),
                ('starter_code', models.JSONField(blank=True, default=dict, help_text='{"python": "class Solution:...", "javascript": "..."}')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('company_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='e.g. ["Google", "Meta", "Amazon"]')),
                ('topic_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='e.g. ["array", "dp", "graph"]')),
                ('leetcode_number', models.PositiveIntegerField(blank=True, help_text='Optional LeetCode problem number for reference', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['leetcode_number', 'title'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['company_tags'], name='idx_question_company_tags'), django.contrib.postgres.indexes.GinIndex(fields=['topic_tags'], name='idx_question_topic_tags'), models.Index(fields=['difficulty'], name='questions_q_difficu_5db314_idx'), models.Index(fields=['is_active'], name='questions_q_is_acti_723019_idx')],
            },
        ),
    ]
